name: tokenspiceenv
dependencies:
  - python=3.8
  - pip
  - numpy
  - matplotlib
  - pip:
    - enforce-typing
    - pytest
    - web3
    - deprecated
    - pycryptodomex
    - tqdm
    - pytz
    - eth-account
    - eth-keys
    - eth-utils
    
