name: Unit Testing and Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.8 ]


    steps:
      - uses: actions/checkout@v2

      - name: Set up Python {{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Ganache-CLI
        run: npm install ganache-cli --global

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt;
          
      - name: Find out what the directory structure looks like.
        run: |
          pwd
          tree

      - name: Compile the contracts
        run: |
          ./compile.sh

      - name: Run Pytest (Just one test)
        run: |
          pytest agents/test/test_DataconsumerAgent.py

      - name: Run Entire Suite of Tests Along With Code Coverage Analysis
        run: |
          coverage run -m pytest
          coverage xml
          export CODACY_PROJECT_TOKEN=${{ secrets.CODACY_PROJECT_TOKEN }}
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
